sudo: true

services:
  - docker

before_install:
  - docker build -t petrepatrasc/docker-ubuntu .

script:
  - docker run -d --name apache petrepatrasc/docker-ubuntu

after_script:
  - sudo docker kill $(docker ps -q);
  - sudo docker rm $(docker ps -aq);
  - sudo docker rmi $(docker images -q);
